version: "3.7"
services:
  tinc:
    image: robertfent1/tinc-rpi-client
    ports:
      - "655:655/tcp"
      - "655:655/udp"
    volumes:
      - ./tinc:/etc/tinc
    cap_add:
      - NET_ADMIN
    network_mode: host
    dns: 8.8.8.8
    restart: always
    container_name: tinc-rpi
